name: clean_data
version: 0.4.17
author: Clean Team <clean@vacuumlabs.com>
description: Support for automatical data synchronization among collections.
homepage: http://cleandart.github.io/clean_data/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://cleandart.github.io/clean_data/
dependencies:
  mock: any
  persistent: any
  clean_sync: any
dev_dependencies:
  hop: any
  unittest: '>=0.11.0'
dependency_overrides:
  persistent:
    path: /home/brandys11/VacuumLabs/persistent
  clean_sync:
    path: /home/brandys11/VacuumLabs/clean_sync
